apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-data
  namespace: navidrome
  labels:
    app: navidrome
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-data
  namespace: navidrome
  labels:
    app: navidrome
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
